### ISSUE TITLE
auth.test API call made on every request

### ISSUE THREAD

**Issue by nauxliu** [seratch/slack-edge#50]
While reviewing the Vercel request logs, I noticed that an API call to auth.test is being made on every request.

**Questions:**
1. Is this auth.test API call necessary?
2. Is this the expected behavior?

<img width="415" alt="image" src="https://github.com/user-attachments/assets/ae5ecce4-d2d3-456a-81ad-5fc4924bfc82">

**Comment by seratch** [comment]
Hi @nauxliu, thanks for asking the questions. 

Yes, this is an intentional API call to fetch metadata associated with the bot token: https://github.com/seratch/slack-edge/blob/main/src/authorization/single-team-authorize.ts. The metadata will be used in subsequent middleware and listeners. 

If you run your app for a specific, single workspace and you desire to skip the API call, you can pass your own authorize function, which skips the API call and sets static data instead, to SlackApp constructor. Having a cache layer for the auth.test API response within your authorize function could be an alternative approach.

If everything is clear now, could you close this issue? If you have further questions, feel free to write in.
